#!/usr/bin/bash
#
# Put customizations to your image in this file.

KUMQUAT_VERSION='0.1.13'

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages."
mkdir -p /opt/kumquat

# Download and extract kumquat to /opt/kumquat
echo "* Download and extract kumquat to /opt/kumquat"
curl -L "https://github.com/wiedi/kumquat/archive/v${KUMQUAT_VERSION}.tar.gz" | tar xz -C /opt/kumquat --strip-components=1

# Setup permissions for kumquat folder
echo "* Setup permissions for kumquat folder"
chown -R www:www /opt/kumquat

# Install missing dependencies via pip
echo "* Install missing dependencies via pip"
pip install django django-bootstrap3 django-messagegroups

# Setup gunicorn
echo "* Setup gunicorn"
mkdir -p /opt/local/etc/gunicorn
svccfg import /tmp/gunicorn.xml

# Create nginx ssl folder
echo "* Create nginx ssl folder"
mkdir -p /opt/local/etc/nginx/ssl

# Copy default (basic) kumquat settings
echo "* Copy default (basic) kumquat settings"
cp /tmp/kumquat-settings.py /opt/kumquat/kumquat_web/settings.py
rm /tmp/kumquat-settings.py

echo "* Cleaning up"
rm -rf /root/*
sm-prepare-image -y
